### ISSUE TITLE
Assign role to user andapply exceptions

### ISSUE THREAD

**Issue by ferhilonegro** [JosephSilber/bouncer#138] opened 2016-11-10 15:22 UTC
I have de following role and abilities, this code was extracted from the seed file

```
        $createUser = Ability::create(['name' => 'create-users', 'title'=>'Can Create Users']);
        $editUser = Ability::create(['name' => 'edit-users', 'title'=>'Can Edit Users']);
        $deleteUser = Ability::create(['name' => 'delete-user', 'title'=>'Can Delete Users']);
        $banUser = Ability::create(['name' => 'ban-user', 'title'=>'Can Ban Users']);
        $resetPassword = Ability::create(['name' => 'reset-pass', 'title'=>'Can Reset Password']);

        Bouncer::allow('staff')->to($createUser);
        Bouncer::allow('staff')->to($editUser);
        Bouncer::allow('staff')->to($deleteUser);
        Bouncer::allow('staff')->to($banUser);
        Bouncer::allow('staff')->to($resetPassword);
```

I want to assign the Staff role to user 01 and user02, but for user01 I do not want him to have the ability to reset his password. I thought about doing this

```
$ user-> assign ( 'staff')
$ user01-> disallow ( 'reset-password')
```
I wonder if it is correct, or how should I store the roles and permissions for this user?

**Comment by JosephSilber** [comment] 2016-11-11 03:56
Closing this as a duplicate of #45

**Closed by JosephSilber** 2016-11-11 03:56 UTC
