### ISSUE TITLE
Can't seem to get OwnedVia to fire

### ISSUE THREAD

**Issue by DeanWard** [JosephSilber/bouncer#332] opened 2018-08-13 11:34 UTC
Hello,

First of all, thank you for Bouncer! 

I'm trying to get ownedVia to work but the closure I pass is never fired.

# My Setup
## Users Table
| id |customer_id |
|---|---|
|1|2|
|2|3|
|3|2|
|4|2|
|5|null|

## Customers Table
| id |account_manager_id|
|---|---|
|2|5|
|3|8|

## Account Manager
```php
Bouncer::allow('Account Manager')->toOwn(User::class)->to(['show','update','delete']);
```

## AppServiceProvider@boot

```php
Bouncer::ownedVia(User::class, function ($model, $user) {
            \Log::info('checking ',[$model,$user]);
            if(Bouncer::is($user)->an('Account Manager')) {
                if($model->customer->account_manager_id == $user->id) {
                    return true;
                }
                return false;
            }
        });
```
User 5 should be able to update users 1,3,4 but permission is always denied.

To debug I put the log code into the closure but nothing is ever logged, it looks like the closure is not being called?

Would really appreciate any help you can give on this one, please?

**Comment by JosephSilber** [comment] 2018-08-13 13:07
The `ownedVia` callback will only be called if the user actually has permission to do the given action on owned models. It seems your logged-in user is not an `Account Manager` (you haven't shown us your `assigned_roles` table).

---

BTW, why are you checking `Bouncer::is($user)->an('Account Manager')` within the `ownedVia` callback? This callback just establishes ownership. The check for whether owned models can be accessed is done internally by Bouncer.

This is all you need:

```php
Bouncer::ownedVia(User::class, function ($model, $user) {
    return $model->customer->account_manager_id == $user->id;
});
```

**Comment by DeanWard** [comment] 2018-08-13 13:14
Thanks for the pointers. I'll take a look if there are issues somewhere else.

I'm checking the role inside the closure because i'll have a user level above Account Manager that can manage users owned by companies owned managed by account managers that THEY manage.

In short different roles will have different ownership rules. Am I going about that in the wrong way?

Thanks again

Dean

**Comment by JosephSilber** [comment] 2018-08-16 14:37
@DeanWard I can't seem to reproduce this problem.

Can you create a minimal repo where I can see this problem reproduced? Just a clean Laravel+Bouncer install, then set up your roles/permissions however you like, showing this problem.

**Comment by JosephSilber** [comment] 2018-08-26 14:07
Again, I can't reproduce this issue. I'm closing it for now, but if you can provide a reproduction, fell free to open a new issue.

**Closed by JosephSilber** 2018-08-26 14:07 UTC
Labels: support
