### ISSUE TITLE
When a user's ability is removed, the role's ability is removed.

### ISSUE THREAD

**Issue by garus12** [JosephSilber/bouncer#335] opened 2018-08-16 14:51 UTC
Hello!

I apologize in advance for my English.

Found a bug which manifests itself only under certain conditions. To repeat, run on a clean base from the user with `id == 1`.

Create the `admin` role with the ability `create-posts` and `create-comments`.
```
Bouncer::allow('admin')->to([
    'create-posts',
    'create-comments'
]);
```
And add the ability to `create-posts` to the user.
```
Bouncer::allow($user)->to('create-posts');
```
Got this result in the table `permissions`.

ability_id | entity_id | entity_type | forbidden | scope
| -- | -- | -- | -- | -- |
| 2 | 1 | roles | 0 | NULL
| 1 | 1 | roles | 0 | NULL
| 1 | 1 | App\User | 0 | NULL

Now remove the `create-posts` ability from the user.
```
Bouncer::disallow($user)->to('create-posts');
```

I expect this result in the database:

ability_id | entity_id | entity_type | forbidden | scope
| -- | -- | -- | -- | -- |
| 2 | 1 | roles | 0 | NULL
| 1 | 1 | roles | 0 | NULL

But in reality get:

ability_id | entity_id | entity_type | forbidden | scope
| -- | -- | -- | -- | -- |
| 2 | 1 | roles | 0 | NULL

Along with the user's ability, the role's ability was removed. Is this a bug or am I just missing something? Thanks in advance!

Version used: v1.0.0-rc.1

**Comment by JosephSilber** [comment] 2018-08-22 00:36
I think this is a duplicate of #278 (which is fixed in master).

If it is, please close this issue.

**Closed** 2018-08-26 14:07 UTC
