### ISSUE TITLE
Cache give reverse effect

### ISSUE THREAD

**Issue by aden16rus** [JosephSilber/bouncer#351] opened 2018-09-21 23:00 UTC
i have laravel 5.6, target page contain loop with 10 iterations of product, each iteration check permission.
by default product list with 10 items give 20 duplicated queries for checking access. When i add `Bouncer::cache();` to boot function of `AppServiceProvider` i see 40 duplicated queries.
Anyway cache not working. i try change cache type to file and database but it not help me.

**Comment by sebdesign** [comment] 2018-09-24 17:13
This is a duplicate of #347 .

**Closed** 2018-10-08 12:51 UTC
