### ISSUE TITLE
Best practices for default auth/guest permissions?

### ISSUE THREAD

**Issue by Axieum** [JosephSilber/bouncer#391] opened 2019-02-20 04:52 UTC
An authenticated user (`\App\User::class`) should be able to `['update', 'delete', 'see-email']` of their own user, but also be able `'view'` other users.

```php
Bouncer::allow('user')->to('view', \App\User::class);
Bouncer::allow('user')->toOwn(\App\User::class)
                      ->to(['update', 'delete', 'see-email']);
```

Then authorising a request in the controller method:
```php
$this->authorize('view', $user);
```

Now, this requires that every registered user is assigned the default `user` role, which in my opinion does not seem necessary to store in the database as it can be "assumed" that a registered user inherits the `user` role.

Is there a way to define a set of default permissions for an authenticated user, and possibly default permissions for guests (unauthenticated users)?

**Comment by Axieum** [comment] 2019-02-20 13:53
I believe this could be achieved through a config file and intercepting Laravel's gate - am yet to attempt.

https://laravel.com/docs/5.7/authorization#intercepting-gate-checks

**Comment by JosephSilber** [comment] 2019-02-20 19:59
> Now, this requires that every registered user is assigned the default `user` role, which in my opinion does not seem necessary

Agree. I have this on my list of features for the future.

Duplicate of #319

**Closed** 2019-02-20 19:59 UTC
Labels: proposal

**Comment by JosephSilber** [comment] 2019-02-25 03:55
> Is there a way to define a set of default permissions for an authenticated user

I just [pushed some code to master to add support for this](https://github.com/JosephSilber/bouncer/issues/319#issuecomment-466863070).

Please check it out, and let me know if it works for you.

**Comment by Axieum** [comment] 2019-02-26 09:21
This works very nicely, thank you!

See Axieum/laravel-api-boilerplate@543376c60ea14751f10fac97fc7d376a7665015f
