### ISSUE TITLE
Get user roles in a View blade 

### ISSUE THREAD

**Issue by uicabpatweyler** [JosephSilber/bouncer#497] opened 2020-01-10 18:39 UTC
Hello, good day. I am starting with the use of ACL with BOUNCER. In my view blade I have something like this:

`
@foreach($users as $user)

    {{ $user->name }}

    {{ $user->getRoles()  }}
@endforeach
`

The above shows me the name of the user and the role or roles assigned. However these are shown as follows:

`[ "RoleName1", "RoleName2" ]`

Inside square brackets and double quotes. 

How could I show it without the square brackets and quotes? I thank you for your help.

Regards.

**Comment by woottonn** [comment] 2020-01-13 15:36
You could do something like this

```
@foreach(Auth::user()->getRoles() as $role)
    {{ $role }}
@endforeach
```

**Comment by JosephSilber** [comment] 2020-01-17 03:58
This seems to be a duplicate of #499

**Closed by JosephSilber** 2020-01-17 03:58 UTC
