### ISSUE TITLE
Too many queries to check abilities

### ISSUE THREAD

**Issue by divdax** [JosephSilber/bouncer#345] opened 2018-09-10 07:54 UTC
Hey guys,

i'm new to this package and like it so far. Thanks for the great package!

**Using:**
- Laravel 5.7
- Bouncer v1.0.0-rc.3

I have a page to list some data and check the ability for every row in my template with blades @can() helper, so when i've a list of 50 rows there are fired about 400 queries to check the ability 😱 

In my `AppServiceProvider` i added the `\Bouncer::cache();` in the boot method.
When updating the roles i'm using `\Bouncer::refresh();` after saving.

My current cache driver is `file` but also tries `redis`.

What i'm missing?

**Comment by MithrandirDK** [comment] 2018-09-26 12:03
I have the same problem when generating a list of ~200 elements and checking a couple of permissions on each element, there are some 4 queries per element.

I suspect one part of the issue is that it fetches all relevant abilities and checks them afterwards. This means that even if a user has an ability for any entity, Bouncer will still (try to) fetch the more specific abilities (does this user have the particular ability on the particular entity of the particular type).

In my current use case, I would benefit from a toggle disabling per-entity permissions, since we only have "This user has this ability for all entities of this type" and "This user has this ability for all his own entities of this type" and "This user does not have this ability for any entity of this type" which can be statically cached and thus only a few queries per request rather than several queries per element.

**Comment by raysn0w** [comment] 2018-10-07 23:36
I'm having the same issue, was this ever fixed?

**Comment by JosephSilber** [comment] 2018-10-08 12:50
Closing this as a duplicate of #347.

**Closed by JosephSilber** 2018-10-08 12:50 UTC
