### ISSUE TITLE
Does Bouncer support Blade?

### ISSUE THREAD

**Issue by avivronen** [JosephSilber/bouncer#42] opened 2016-01-22 13:38 UTC
Hi,
Can we use something like:

@role('admin')
//..
@endrole

Thanks!

**Comment by Arcesilas** [comment] 2016-01-22 13:43
Hi,

This question has already been discussed in #36.

**Comment by JosephSilber** [comment] 2016-01-22 14:07
Closing this as a duplicate of #36. I also added a little more detail there now.

If you still have any questions about this, feel free to comment on that thread.

**Closed by JosephSilber** 2016-01-22 14:07 UTC
