### ISSUE TITLE
$this is not accesible in static context

### ISSUE THREAD

**Issue by midorikocak** [JosephSilber/bouncer#251] opened 2018-01-16 15:22 UTC
Hello,

My Php version is 7.2.0 and I am using PHPStorm 2017.3. When I do a fresh install Bouncer using command 
`composer require silber/bouncer v1.0.0-beta.5`, PHPStorm raises a warning on file src/Bouncer.php on line 408 and 421.

Here is a screenshot:
<img width="930" alt="screen shot 2018-01-16 at 16 01 59" src="https://user-images.githubusercontent.com/545472/34996239-4cbe350c-fad9-11e7-8b35-f8dd312ab631.png">

Is this normal?

Thanks.

**Comment by JosephSilber** [comment] 2018-01-16 17:34
This is a duplicate of #245.

It's been fixed in master. In the meantime, you can either use master or call the method on the `Models` class directly.

**Closed by JosephSilber** 2018-01-16 17:34 UTC
