### ISSUE TITLE
Unable to getRoles of Auth::user()

### ISSUE THREAD

**Issue by acidjazz** [JosephSilber/bouncer#283] opened 2018-05-03 23:32 UTC
`Auth::user()->getRoles();` gives me 

`Method Illuminate\Database\Query\Builder::getRoles does not exist.`

Although I can run `Auth::user()->load('roles');` just fine and see my admin role.

I have no other issues and the installation went smooth

here is my User model:

```php
namespace App\Models;

use App\Models\Collection;
use App\Models\Provider;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
  
use Notifiable;
  use HasRolesAndAbilities;

  public function getJWTIdentifier()
  {
    return $this->getKey();
  }

  public function getJWTCustomClaims()
  {
    return [];
  }

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'email', 'name', 'username', 'type', 'provider', 'avatar',
  ];

  /**
	 * Get the route key for the model.
	 * See https://laravel.com/docs/5.4/routing#route-model-binding
	 *
	 * @return string
	 */
	public function getRouteKeyName()
	{
		return 'username';
	}

  public function collections()
  {
    return $this->hasMany(Collection::class);
  }

  public function providers()
  {
    return $this->hasMany(Provider::class);
  }

  public function getUnreadNotificationsCountAttribute()
  {
    return $this->unreadNotifications()->count();
  }

  public function receivesBroadcastNotificationsOn()
  {
    return 'App.Models.User.'.$this->id;
  }

}
```

**Comment by JosephSilber** [comment] 2018-05-03 23:56
Closing this a s a duplicate of #281.

**Closed** 2018-05-03 23:56 UTC

**Comment by acidjazz** [comment] 2018-05-04 00:04
@JosephSilber maybe skip on having documentation for features that aren't available yet? or specify in the docs that they are only in master?
