### ISSUE TITLE
oracle issue with level field

### ISSUE THREAD

**Issue by nophaa** [JosephSilber/bouncer#233] opened 2017-11-08 03:23 UTC
I receive the Oracle error 01788 Connect By Clause Required in query block, because there is a level field which is need connect by in oracle.

**Comment by JosephSilber** [comment] 2017-11-09 03:57
Duplicate of #221.

I don't have any experience with Oracle databases, and don't have an Oracle DB set up to test with.

I'd accept a PR that fixes this. I myself can't do anything about it.

**Closed by JosephSilber** 2017-11-09 03:57 UTC
