### ISSUE TITLE
Exception at running an "allow check", in Oracle database ["level keyword" ; "ORA-01788"]

### ISSUE THREAD

**Issue by Gaven-ar** [JosephSilber/bouncer#221] opened 2017-10-10 12:30 UTC
Hello, I have a question / problem / error to solve. When I try to run the `Bouncer::allow` check (over an ability) I get a database error. The Laravel project is connected to an Oracle database, and seems like there's a conflict with the "_level_" column name, at the "_role_" table (that I assigned with another name).

**The exception I get running the Bouncer ckecking is:**

> ORA-01788: CONNECT BY clause required in this query block

That don't say much to me, but in the statement field there's a big query with the next segment:

> or "level" < (select max(level) from

Seems like is missing quotes on the second ocurrence of the "level" word.

**How should I run the Bouncer check to avoid this error?**

Thank you. And congrats for the good job with this Laravel package.

**Comment by JosephSilber** [comment] 2017-10-10 14:45
If you manually run the query with quotes around that `limit` column, does it work?

I don’t have an Oracle database to test this on.

**Comment by JosephSilber** [comment] 2017-10-10 14:47
I unfortunately do not have Oracle DB to test this on. If you can figure out what’s wrong with the query, we’ll see how we can fix it.

Do you know how to manually modify the query to make it work? That’s be the first step to figuring out what’s wrong.

**Comment by Gaven-ar** [comment] 2017-10-10 15:06
I think that what's wrong with the query is the reference to the "limit"column without quotes, in the syntax.

But knowing how to modify the query that Bouncer or Laravel generate from calling the "allow" check is more than the first step. It is what I need to do.

Anyway, if I find something useful I would comment it here.

**Comment by JosephSilber** [comment] 2017-10-10 16:08
I meant to ask if you take the raw query and run it directly in the DB, do you know how to tweak it so that it runs properly?

That’s the first step.

**Comment by Gaven-ar** [comment] 2017-10-10 16:59
Ah ok.. Well, running the raw query in the DataBase I get the same error message.
I found out that the error also is the same if I run `Bouncer::allows` or `$this->authorize` (in a controller class). So maybe is something with the Query Builder.

**Comment by JosephSilber** [comment] 2017-10-11 15:24
Closing this pending further details.

**Closed by JosephSilber** 2017-10-11 15:24 UTC

**Comment by Gaven-ar** [comment] 2017-10-12 10:42
I updated the post title and the content, because I came to this situation with the "level" reserved word, and not "limit". So I correct de text. Anyway, is the same situation.
I asked for this issue to the "_yajra/laravel-oci8_" GitHub package, that I use to connect the project to the Database. But I get no solution, just a suggest about update Laravel to version 5.5 (now i'm at 5.2).

**Comment by cativo23** [comment] 2020-05-07 01:00
@Gaven-ar Hi, I wanted to know if you were able to solve this? I have the same problem and I can't solve it... I'm using Laravel 7

**Comment by cativo23** [comment] 2020-05-07 02:49
Hello, I will leave this in case someone else presents this problem, I could solve it by changing

 `$query->selectRaw('max(level)') `

to 

 `$query->selectRaw("max('level')")`

in _vendor/silber/bouncer/src/Database/Queries/Abilities.php_ on **line 83**

The problem is that the column in the roles table has a column called **_level_**, but it turns out that it is a word reserved for the Oracle database and since this is a **selectRaw**, the driver for Oracle (yajra/laravel-oci8) cannot translate it to a valid query in Oracle. 
As a suggestion I think it would be good to avoid using Raw queries so that the different database drivers can work properly and in case it is not possible, I think it would be good to let people know in which databases it has been tested and that it might not work properly in others because of these Raw Queries.

**Comment by rconte84** [comment] 2021-01-22 11:35
Same here!

This is the correct solution for Oracle working also on Mysql and *maybe* all others database.

`$query->selectRaw('max("LEVEL")')`

Tested and working
