### ISSUE TITLE
Can't get all abilities of role model

### ISSUE THREAD

**Issue by FinnJanik** [JosephSilber/bouncer#280] opened 2018-04-25 14:36 UTC
Hey again,

I got another interresting one... 😃 
I created a custom role model in the App directory. I just extended the default Bouncer role model and added some functions and another package to log activity on the model (create, update, delete). 
I implemented it like suggested here: https://github.com/JosephSilber/bouncer/issues/13

First I didn't register the Bouncer::useRoleModel() in the AppServiceProvider. Everything seemed to work fine, but the getAbilties() function returned an empty collection when used on my custom model. 

```
//Empty collection returned
$role = Role::find(1);
$role->getAbilities();

//Returned full list of abilities
$role = Bouncer::role()::find(1);
$role->getAbilities();
```

Then I went on and registered the Bouncer::useRoleModel() in the AppServiceProvider. Now the getAbilities() function doesn't work on Bouncer anymore too.

```
//Empty collection returned
$role = Role::find(1);
$role->getAbilities();

//Now also an empty collection
$role = Bouncer::role()::find(1);
$role->getAbilities();
```

This time I have now clue how this happened. I actually tried a lot of things like implementing the Traits directly and so on, nothing worked..

Kind regards,
Finn Janik

**Comment by JosephSilber** [comment] 2018-05-01 02:04
Nothing I see here would suggest there's anything wrong. Are you sure your role actually has abilities assigned to it?

**Comment by FinnJanik** [comment] 2018-05-03 08:53
Yes I'm sure. As I said if I user the Bouncer model directly I get all the abilities. I tried it in the artisan console and in the controller. Both times with the same effect..
I just can't get the abilties of the role from my model.
How can we go on about that?

**Comment by jalvjim** [comment] 2018-05-07 13:34
Hi!
I am dealing with the same problem, but i think this happens because the relations from DB model are statically linked to Bouncer's Role Model and your instance belonging to another different class you don't get the same results

**Comment by tobias-kuendig** [comment] 2018-07-17 07:50
I had a similar problem. 

The `entity_type` in the `permissions` table was saved as `roles`. If I run a query  a `entity_type` of `App\Role` was used.

In my case the problem was that I did not call `useRoleModel`. I know this is not the solution to your problem but it might help someone else.

```php
// AppServiceProvider.php -> boot()
\Bouncer::useRoleModel(App\Role::class);
```

**Comment by JosephSilber** [comment] 2018-07-23 15:17
I'm still not clear what the issue is here.

Anyway, it may be related to [this](https://github.com/JosephSilber/bouncer/issues/306#issuecomment-401045612). If so, try registering your custom model with the morph map:

```php
use Bouncer;
use App\Role;
use Illuminate\Database\Eloquent\Relations\Relation;

public function boot()
{
    Bouncer::useRoleModel(Role::class);

    Relation::morphMap([Role::class]);
}
```

**Comment by JosephSilber** [comment] 2018-08-02 18:05
Is this still an issue after registering your custom models with the morph map?

**Closed** 2018-08-02 20:42 UTC
Labels: support

**Comment by liranAtli** [comment] 2018-12-10 09:54
any solution? 
i got getAbilities() always empty array.

ty

**Comment by shyammtp** [comment] 2020-12-18 10:44
> ```
> 
> use Illuminate\Database\Eloquent\Relations\Relation;
> ```
In the Permission table, entity_type is defined as "roles" but the Table name for roles "custom_roles". 
This line fix that entity_type for me.
Relation::morphMap(['roles' => Role::class]);

**Comment by shyammtp** [comment] 2020-12-18 10:45
This works for me, 
`Relation::morphMap(['roles' => Role::class]);`
